#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup_env.sh
#
# Creates the conda environment for reasoning_flow, installs all deps,
# and registers it as a Jupyter kernel (for NJIT OnDemand notebooks).
#
# Run ONCE from the root of the repo:
#   bash setup_env.sh
#
# After this, always activate with:
#   conda activate reasoning_flow
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

ENV_NAME="reasoning_flow"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "══════════════════════════════════════════════════════════════════"
echo " reasoning_flow — Environment Setup"
echo " Repo root: $REPO_ROOT"
echo " $(date)"
echo "══════════════════════════════════════════════════════════════════"

# ── Verify conda is available ─────────────────────────────────────────────────
if ! command -v conda &> /dev/null; then
    echo "ERROR: conda not found. On NJIT OnDemand, load it with:"
    echo "  module load anaconda3"
    exit 1
fi
echo "conda found: $(conda --version)"

# ── Remove old env if it exists ───────────────────────────────────────────────
if conda env list | grep -q "^${ENV_NAME} "; then
    echo ""
    echo "Existing env '${ENV_NAME}' found. Removing it..."
    conda env remove -n "$ENV_NAME" -y
fi

# ── Create env from YAML ──────────────────────────────────────────────────────
echo ""
echo "── Creating conda env: ${ENV_NAME} ─────────────────────────────────────"
conda env create -f "$REPO_ROOT/environment.yml"

# ── Activate and verify ───────────────────────────────────────────────────────
echo ""
echo "── Verifying installation ───────────────────────────────────────────────"

# Run checks inside the env
conda run -n "$ENV_NAME" python - << 'PYCHECK'
import sys
print(f"Python: {sys.version}")

import torch
print(f"PyTorch: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

import transformers
print(f"Transformers: {transformers.__version__}")

import geoopt
print(f"geoopt: {geoopt.__version__}")

import numpy as np
print(f"NumPy: {np.__version__}")

import pandas as pd
print(f"Pandas: {pd.__version__}")

import scipy
print(f"SciPy: {scipy.__version__}")

print("\n✅ All core packages verified.")
PYCHECK

# ── Register as Jupyter kernel ────────────────────────────────────────────────
echo ""
echo "── Registering Jupyter kernel ───────────────────────────────────────────"
conda run -n "$ENV_NAME" python -m ipykernel install \
    --user \
    --name "$ENV_NAME" \
    --display-name "Python (reasoning_flow)"
echo "Kernel registered: 'Python (reasoning_flow)'"
echo "It will appear in NJIT OnDemand → Jupyter → New Kernel"

# ── Create .env file for project ──────────────────────────────────────────────
echo ""
echo "── Writing .env config ──────────────────────────────────────────────────"
cat > "$REPO_ROOT/.env" << EOF
# reasoning_flow project environment
# Auto-generated by setup_env.sh — do not edit manually

CONDA_ENV=reasoning_flow
PROJECT_ROOT=$REPO_ROOT
HF_HOME=$REPO_ROOT/.hf_cache
TRANSFORMERS_CACHE=$REPO_ROOT/.hf_cache
HF_DATASETS_CACHE=$REPO_ROOT/.hf_cache/datasets
CUDA_VISIBLE_DEVICES=0
TOKENIZERS_PARALLELISM=false
EOF
echo ".env written to $REPO_ROOT/.env"

# ── Print activation instructions ────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════════════════"
echo " Setup complete! $(date)"
echo ""
echo " To activate:"
echo "   conda activate $ENV_NAME"
echo ""
echo " To run the smoke test:"
echo "   conda activate $ENV_NAME && bash quick_test.sh"
echo ""
echo " To run the full pipeline:"
echo "   conda activate $ENV_NAME && bash run_deception_pipeline.sh"
echo ""
echo " HuggingFace cache will be stored at:"
echo "   $REPO_ROOT/.hf_cache"
echo "   (models download here — keeps them in your project dir)"
echo "══════════════════════════════════════════════════════════════════"
